# DEFINE SCORES
scoreboard players set @s edit 20

# COM MÁSCARA *********************

execute @s ~ ~ ~ function _processes/_brushes/_small/_call/_mask_on

# SEM MÁSCARA *********************

execute @s [scores={mask_block=0}] ~ ~ ~ function _processes/_brushes/_small/_call/_mask_off

# TÍTULO

execute @s [scores={paint_block=1}] ~ ~ ~ title @s actionbar §a§lBrush small air
execute @s [scores={paint_block=2}] ~ ~ ~ title @s actionbar §a§lBrush small stone
execute @s [scores={paint_block=3}] ~ ~ ~ title @s actionbar §a§lBrush small grass
execute @s [scores={paint_block=4}] ~ ~ ~ title @s actionbar §a§lBrush small dirt
execute @s [scores={paint_block=5}] ~ ~ ~ title @s actionbar §a§lBrush small cobblestone
execute @s [scores={paint_block=6}] ~ ~ ~ title @s actionbar §a§lBrush small planks
execute @s [scores={paint_block=7}] ~ ~ ~ title @s actionbar §a§lBrush small sapling
execute @s [scores={paint_block=8}] ~ ~ ~ title @s actionbar §a§lBrush small bedrock
execute @s [scores={paint_block=9}] ~ ~ ~ title @s actionbar §a§lBrush small flowing_water
execute @s [scores={paint_block=10}] ~ ~ ~ title @s actionbar §a§lBrush small water
execute @s [scores={paint_block=11}] ~ ~ ~ title @s actionbar §a§lBrush small flowing_lava
execute @s [scores={paint_block=12}] ~ ~ ~ title @s actionbar §a§lBrush small lava
execute @s [scores={paint_block=13}] ~ ~ ~ title @s actionbar §a§lBrush small sand
execute @s [scores={paint_block=14}] ~ ~ ~ title @s actionbar §a§lBrush small gravel
execute @s [scores={paint_block=15}] ~ ~ ~ title @s actionbar §a§lBrush small gold_ore
execute @s [scores={paint_block=16}] ~ ~ ~ title @s actionbar §a§lBrush small iron_ore
execute @s [scores={paint_block=17}] ~ ~ ~ title @s actionbar §a§lBrush small coal_ore
execute @s [scores={paint_block=18}] ~ ~ ~ title @s actionbar §a§lBrush small log
execute @s [scores={paint_block=19}] ~ ~ ~ title @s actionbar §a§lBrush small leaves
execute @s [scores={paint_block=20}] ~ ~ ~ title @s actionbar §a§lBrush small sponge
execute @s [scores={paint_block=21}] ~ ~ ~ title @s actionbar §a§lBrush small glass
execute @s [scores={paint_block=22}] ~ ~ ~ title @s actionbar §a§lBrush small lapis_ore
execute @s [scores={paint_block=23}] ~ ~ ~ title @s actionbar §a§lBrush small lapis_block
execute @s [scores={paint_block=24}] ~ ~ ~ title @s actionbar §a§lBrush small dispenser
execute @s [scores={paint_block=25}] ~ ~ ~ title @s actionbar §a§lBrush small sandstone
execute @s [scores={paint_block=26}] ~ ~ ~ title @s actionbar §a§lBrush small noteblock
execute @s [scores={paint_block=27}] ~ ~ ~ title @s actionbar §a§lBrush small bed
execute @s [scores={paint_block=28}] ~ ~ ~ title @s actionbar §a§lBrush small golden_rail
execute @s [scores={paint_block=29}] ~ ~ ~ title @s actionbar §a§lBrush small detector_rail
execute @s [scores={paint_block=30}] ~ ~ ~ title @s actionbar §a§lBrush small sticky_piston
execute @s [scores={paint_block=31}] ~ ~ ~ title @s actionbar §a§lBrush small web
execute @s [scores={paint_block=32}] ~ ~ ~ title @s actionbar §a§lBrush small tallgrass
execute @s [scores={paint_block=33}] ~ ~ ~ title @s actionbar §a§lBrush small deadbush
execute @s [scores={paint_block=34}] ~ ~ ~ title @s actionbar §a§lBrush small piston
execute @s [scores={paint_block=35}] ~ ~ ~ title @s actionbar §a§lBrush small piston_head
execute @s [scores={paint_block=36}] ~ ~ ~ title @s actionbar §a§lBrush small wool
execute @s [scores={paint_block=37}] ~ ~ ~ title @s actionbar §a§lBrush small yellow_flower
execute @s [scores={paint_block=38}] ~ ~ ~ title @s actionbar §a§lBrush small red_flower
execute @s [scores={paint_block=39}] ~ ~ ~ title @s actionbar §a§lBrush small brown_mushroom
execute @s [scores={paint_block=40}] ~ ~ ~ title @s actionbar §a§lBrush small red_mushroom
execute @s [scores={paint_block=41}] ~ ~ ~ title @s actionbar §a§lBrush small gold_block
execute @s [scores={paint_block=42}] ~ ~ ~ title @s actionbar §a§lBrush small iron_block
execute @s [scores={paint_block=43}] ~ ~ ~ title @s actionbar §a§lBrush small double_stone_slab
execute @s [scores={paint_block=44}] ~ ~ ~ title @s actionbar §a§lBrush small stone_slab
execute @s [scores={paint_block=45}] ~ ~ ~ title @s actionbar §a§lBrush small brick_block
execute @s [scores={paint_block=46}] ~ ~ ~ title @s actionbar §a§lBrush small tnt
execute @s [scores={paint_block=47}] ~ ~ ~ title @s actionbar §a§lBrush small bookshelf
execute @s [scores={paint_block=48}] ~ ~ ~ title @s actionbar §a§lBrush small mossy_cobblestone
execute @s [scores={paint_block=49}] ~ ~ ~ title @s actionbar §a§lBrush small obsidian
execute @s [scores={paint_block=50}] ~ ~ ~ title @s actionbar §a§lBrush small torch
execute @s [scores={paint_block=51}] ~ ~ ~ title @s actionbar §a§lBrush small fire
execute @s [scores={paint_block=52}] ~ ~ ~ title @s actionbar §a§lBrush small mob_spawner
execute @s [scores={paint_block=53}] ~ ~ ~ title @s actionbar §a§lBrush small oak_stairs
execute @s [scores={paint_block=54}] ~ ~ ~ title @s actionbar §a§lBrush small chest
execute @s [scores={paint_block=55}] ~ ~ ~ title @s actionbar §a§lBrush small redstone_wire
execute @s [scores={paint_block=56}] ~ ~ ~ title @s actionbar §a§lBrush small diamond_ore
execute @s [scores={paint_block=57}] ~ ~ ~ title @s actionbar §a§lBrush small diamond_block
execute @s [scores={paint_block=58}] ~ ~ ~ title @s actionbar §a§lBrush small crafting_table
execute @s [scores={paint_block=59}] ~ ~ ~ title @s actionbar §a§lBrush small wheat
execute @s [scores={paint_block=60}] ~ ~ ~ title @s actionbar §a§lBrush small farmland
execute @s [scores={paint_block=61}] ~ ~ ~ title @s actionbar §a§lBrush small furnace
execute @s [scores={paint_block=62}] ~ ~ ~ title @s actionbar §a§lBrush small lit_furnace
execute @s [scores={paint_block=63}] ~ ~ ~ title @s actionbar §a§lBrush small standing_sign
execute @s [scores={paint_block=64}] ~ ~ ~ title @s actionbar §a§lBrush small wooden_door
execute @s [scores={paint_block=65}] ~ ~ ~ title @s actionbar §a§lBrush small ladder
execute @s [scores={paint_block=66}] ~ ~ ~ title @s actionbar §a§lBrush small rail
execute @s [scores={paint_block=67}] ~ ~ ~ title @s actionbar §a§lBrush small stone_stairs
execute @s [scores={paint_block=68}] ~ ~ ~ title @s actionbar §a§lBrush small wall_sign
execute @s [scores={paint_block=69}] ~ ~ ~ title @s actionbar §a§lBrush small lever
execute @s [scores={paint_block=70}] ~ ~ ~ title @s actionbar §a§lBrush small stone_pressure_plate
execute @s [scores={paint_block=71}] ~ ~ ~ title @s actionbar §a§lBrush small iron_door
execute @s [scores={paint_block=72}] ~ ~ ~ title @s actionbar §a§lBrush small wooden_pressure_plate
execute @s [scores={paint_block=73}] ~ ~ ~ title @s actionbar §a§lBrush small redstone_ore
execute @s [scores={paint_block=74}] ~ ~ ~ title @s actionbar §a§lBrush small lit_redstone_ore
execute @s [scores={paint_block=75}] ~ ~ ~ title @s actionbar §a§lBrush small unlit_redstone_torch
execute @s [scores={paint_block=76}] ~ ~ ~ title @s actionbar §a§lBrush small redstone_torch
execute @s [scores={paint_block=77}] ~ ~ ~ title @s actionbar §a§lBrush small stone_button
execute @s [scores={paint_block=78}] ~ ~ ~ title @s actionbar §a§lBrush small snow_layer
execute @s [scores={paint_block=79}] ~ ~ ~ title @s actionbar §a§lBrush small ice
execute @s [scores={paint_block=80}] ~ ~ ~ title @s actionbar §a§lBrush small snow
execute @s [scores={paint_block=81}] ~ ~ ~ title @s actionbar §a§lBrush small cactus
execute @s [scores={paint_block=82}] ~ ~ ~ title @s actionbar §a§lBrush small clay
execute @s [scores={paint_block=83}] ~ ~ ~ title @s actionbar §a§lBrush small reeds
execute @s [scores={paint_block=84}] ~ ~ ~ title @s actionbar §a§lBrush small jukebox
execute @s [scores={paint_block=85}] ~ ~ ~ title @s actionbar §a§lBrush small fence
execute @s [scores={paint_block=86}] ~ ~ ~ title @s actionbar §a§lBrush small pumpkin
execute @s [scores={paint_block=87}] ~ ~ ~ title @s actionbar §a§lBrush small netherrack
execute @s [scores={paint_block=88}] ~ ~ ~ title @s actionbar §a§lBrush small soul_sand
execute @s [scores={paint_block=89}] ~ ~ ~ title @s actionbar §a§lBrush small glowstone
execute @s [scores={paint_block=90}] ~ ~ ~ title @s actionbar §a§lBrush small portal
execute @s [scores={paint_block=91}] ~ ~ ~ title @s actionbar §a§lBrush small lit_pumpkin
execute @s [scores={paint_block=92}] ~ ~ ~ title @s actionbar §a§lBrush small cake
execute @s [scores={paint_block=93}] ~ ~ ~ title @s actionbar §a§lBrush small unpowered_repeater
execute @s [scores={paint_block=94}] ~ ~ ~ title @s actionbar §a§lBrush small powered_repeater
execute @s [scores={paint_block=95}] ~ ~ ~ title @s actionbar §a§lBrush small stained_glass
execute @s [scores={paint_block=96}] ~ ~ ~ title @s actionbar §a§lBrush small trapdoor
execute @s [scores={paint_block=97}] ~ ~ ~ title @s actionbar §a§lBrush small monster_egg
execute @s [scores={paint_block=98}] ~ ~ ~ title @s actionbar §a§lBrush small stonebrick
execute @s [scores={paint_block=99}] ~ ~ ~ title @s actionbar §a§lBrush small brown_mushroom_block
execute @s [scores={paint_block=100}] ~ ~ ~ title @s actionbar §a§lBrush small red_mushroom_block
execute @s [scores={paint_block=101}] ~ ~ ~ title @s actionbar §a§lBrush small iron_bars
execute @s [scores={paint_block=102}] ~ ~ ~ title @s actionbar §a§lBrush small glass_pane
execute @s [scores={paint_block=103}] ~ ~ ~ title @s actionbar §a§lBrush small melon_block
execute @s [scores={paint_block=104}] ~ ~ ~ title @s actionbar §a§lBrush small pumpkin_stem
execute @s [scores={paint_block=105}] ~ ~ ~ title @s actionbar §a§lBrush small melon_stem
execute @s [scores={paint_block=106}] ~ ~ ~ title @s actionbar §a§lBrush small vine
execute @s [scores={paint_block=107}] ~ ~ ~ title @s actionbar §a§lBrush small fence_gate
execute @s [scores={paint_block=108}] ~ ~ ~ title @s actionbar §a§lBrush small brick_stairs
execute @s [scores={paint_block=109}] ~ ~ ~ title @s actionbar §a§lBrush small stone_brick_stairs
execute @s [scores={paint_block=110}] ~ ~ ~ title @s actionbar §a§lBrush small mycelium
execute @s [scores={paint_block=111}] ~ ~ ~ title @s actionbar §a§lBrush small waterlily
execute @s [scores={paint_block=112}] ~ ~ ~ title @s actionbar §a§lBrush small nether_brick
execute @s [scores={paint_block=113}] ~ ~ ~ title @s actionbar §a§lBrush small nether_brick_fence
execute @s [scores={paint_block=114}] ~ ~ ~ title @s actionbar §a§lBrush small nether_brick_stairs
execute @s [scores={paint_block=115}] ~ ~ ~ title @s actionbar §a§lBrush small nether_wart
execute @s [scores={paint_block=116}] ~ ~ ~ title @s actionbar §a§lBrush small enchanting_table
execute @s [scores={paint_block=117}] ~ ~ ~ title @s actionbar §a§lBrush small brewing_stand
execute @s [scores={paint_block=118}] ~ ~ ~ title @s actionbar §a§lBrush small cauldron
execute @s [scores={paint_block=119}] ~ ~ ~ title @s actionbar §a§lBrush small end_portal
execute @s [scores={paint_block=120}] ~ ~ ~ title @s actionbar §a§lBrush small end_portal_frame
execute @s [scores={paint_block=121}] ~ ~ ~ title @s actionbar §a§lBrush small end_stone
execute @s [scores={paint_block=122}] ~ ~ ~ title @s actionbar §a§lBrush small dragon_egg
execute @s [scores={paint_block=123}] ~ ~ ~ title @s actionbar §a§lBrush small redstone_lamp
execute @s [scores={paint_block=124}] ~ ~ ~ title @s actionbar §a§lBrush small lit_redstone_lamp
execute @s [scores={paint_block=125}] ~ ~ ~ title @s actionbar §a§lBrush small double_wooden_slab
execute @s [scores={paint_block=126}] ~ ~ ~ title @s actionbar §a§lBrush small wooden_slab
execute @s [scores={paint_block=127}] ~ ~ ~ title @s actionbar §a§lBrush small cocoa
execute @s [scores={paint_block=128}] ~ ~ ~ title @s actionbar §a§lBrush small sandstone_stairs
execute @s [scores={paint_block=129}] ~ ~ ~ title @s actionbar §a§lBrush small emerald_ore
execute @s [scores={paint_block=130}] ~ ~ ~ title @s actionbar §a§lBrush small ender_chest
execute @s [scores={paint_block=131}] ~ ~ ~ title @s actionbar §a§lBrush small tripwire_hook
execute @s [scores={paint_block=132}] ~ ~ ~ title @s actionbar §a§lBrush small emerald_block
execute @s [scores={paint_block=133}] ~ ~ ~ title @s actionbar §a§lBrush small spruce_stairs
execute @s [scores={paint_block=134}] ~ ~ ~ title @s actionbar §a§lBrush small birch_stairs
execute @s [scores={paint_block=135}] ~ ~ ~ title @s actionbar §a§lBrush small jungle_stairs
execute @s [scores={paint_block=136}] ~ ~ ~ title @s actionbar §a§lBrush small command_block
execute @s [scores={paint_block=137}] ~ ~ ~ title @s actionbar §a§lBrush small beacon
execute @s [scores={paint_block=138}] ~ ~ ~ title @s actionbar §a§lBrush small cobblestone_wall
execute @s [scores={paint_block=139}] ~ ~ ~ title @s actionbar §a§lBrush small flower_pot
execute @s [scores={paint_block=140}] ~ ~ ~ title @s actionbar §a§lBrush small carrots
execute @s [scores={paint_block=141}] ~ ~ ~ title @s actionbar §a§lBrush small potatoes
execute @s [scores={paint_block=142}] ~ ~ ~ title @s actionbar §a§lBrush small wooden_button
execute @s [scores={paint_block=143}] ~ ~ ~ title @s actionbar §a§lBrush small skull
execute @s [scores={paint_block=144}] ~ ~ ~ title @s actionbar §a§lBrush small anvil
execute @s [scores={paint_block=145}] ~ ~ ~ title @s actionbar §a§lBrush small trapped_chest
execute @s [scores={paint_block=146}] ~ ~ ~ title @s actionbar §a§lBrush small light_weighted_pressure_plate
execute @s [scores={paint_block=147}] ~ ~ ~ title @s actionbar §a§lBrush small heavy_weighted_pressure_plate
execute @s [scores={paint_block=148}] ~ ~ ~ title @s actionbar §a§lBrush small unpowered_comparator
execute @s [scores={paint_block=149}] ~ ~ ~ title @s actionbar §a§lBrush small powered_comparator
execute @s [scores={paint_block=150}] ~ ~ ~ title @s actionbar §a§lBrush small daylight_detector
execute @s [scores={paint_block=151}] ~ ~ ~ title @s actionbar §a§lBrush small redstone_block
execute @s [scores={paint_block=152}] ~ ~ ~ title @s actionbar §a§lBrush small quartz_ore
execute @s [scores={paint_block=153}] ~ ~ ~ title @s actionbar §a§lBrush small hopper
execute @s [scores={paint_block=154}] ~ ~ ~ title @s actionbar §a§lBrush small quartz_block
execute @s [scores={paint_block=155}] ~ ~ ~ title @s actionbar §a§lBrush small quartz_stairs
execute @s [scores={paint_block=156}] ~ ~ ~ title @s actionbar §a§lBrush small activator_rail
execute @s [scores={paint_block=157}] ~ ~ ~ title @s actionbar §a§lBrush small dropper
execute @s [scores={paint_block=158}] ~ ~ ~ title @s actionbar §a§lBrush small stained_hardened_clay
execute @s [scores={paint_block=159}] ~ ~ ~ title @s actionbar §a§lBrush small stained_glass_pane
execute @s [scores={paint_block=160}] ~ ~ ~ title @s actionbar §a§lBrush small leaves2
execute @s [scores={paint_block=161}] ~ ~ ~ title @s actionbar §a§lBrush small log2
execute @s [scores={paint_block=162}] ~ ~ ~ title @s actionbar §a§lBrush small acacia_stairs
execute @s [scores={paint_block=163}] ~ ~ ~ title @s actionbar §a§lBrush small dark_oak_stairs
execute @s [scores={paint_block=164}] ~ ~ ~ title @s actionbar §a§lBrush small slime
execute @s [scores={paint_block=165}] ~ ~ ~ title @s actionbar §a§lBrush small barrier
execute @s [scores={paint_block=166}] ~ ~ ~ title @s actionbar §a§lBrush small iron_trapdoor
execute @s [scores={paint_block=167}] ~ ~ ~ title @s actionbar §a§lBrush small prismarine
execute @s [scores={paint_block=168}] ~ ~ ~ title @s actionbar §a§lBrush small sea_lantern
execute @s [scores={paint_block=169}] ~ ~ ~ title @s actionbar §a§lBrush small hay_block
execute @s [scores={paint_block=170}] ~ ~ ~ title @s actionbar §a§lBrush small carpet
execute @s [scores={paint_block=171}] ~ ~ ~ title @s actionbar §a§lBrush small hardened_clay
execute @s [scores={paint_block=172}] ~ ~ ~ title @s actionbar §a§lBrush small coal_block
execute @s [scores={paint_block=173}] ~ ~ ~ title @s actionbar §a§lBrush small packed_ice
execute @s [scores={paint_block=174}] ~ ~ ~ title @s actionbar §a§lBrush small double_plant
execute @s [scores={paint_block=175}] ~ ~ ~ title @s actionbar §a§lBrush small standing_banner
execute @s [scores={paint_block=176}] ~ ~ ~ title @s actionbar §a§lBrush small wall_banner
execute @s [scores={paint_block=177}] ~ ~ ~ title @s actionbar §a§lBrush small daylight_detector_inverted
execute @s [scores={paint_block=178}] ~ ~ ~ title @s actionbar §a§lBrush small red_sandstone
execute @s [scores={paint_block=179}] ~ ~ ~ title @s actionbar §a§lBrush small red_sandstone_stairs
execute @s [scores={paint_block=180}] ~ ~ ~ title @s actionbar §a§lBrush small double_stone_slab2
execute @s [scores={paint_block=181}] ~ ~ ~ title @s actionbar §a§lBrush small stone_slab2
execute @s [scores={paint_block=182}] ~ ~ ~ title @s actionbar §a§lBrush small spruce_fence_gate
execute @s [scores={paint_block=183}] ~ ~ ~ title @s actionbar §a§lBrush small birch_fence_gate
execute @s [scores={paint_block=184}] ~ ~ ~ title @s actionbar §a§lBrush small jungle_fence_gate
execute @s [scores={paint_block=185}] ~ ~ ~ title @s actionbar §a§lBrush small dark_oak_fence_gate
execute @s [scores={paint_block=186}] ~ ~ ~ title @s actionbar §a§lBrush small acacia_fence_gate
execute @s [scores={paint_block=187}] ~ ~ ~ title @s actionbar §a§lBrush small spruce_fence
execute @s [scores={paint_block=188}] ~ ~ ~ title @s actionbar §a§lBrush small birch_fence
execute @s [scores={paint_block=189}] ~ ~ ~ title @s actionbar §a§lBrush small jungle_fence
execute @s [scores={paint_block=190}] ~ ~ ~ title @s actionbar §a§lBrush small dark_oak_fence
execute @s [scores={paint_block=191}] ~ ~ ~ title @s actionbar §a§lBrush small acacia_fence
execute @s [scores={paint_block=192}] ~ ~ ~ title @s actionbar §a§lBrush small spruce_door
execute @s [scores={paint_block=193}] ~ ~ ~ title @s actionbar §a§lBrush small birch_door
execute @s [scores={paint_block=194}] ~ ~ ~ title @s actionbar §a§lBrush small jungle_door
execute @s [scores={paint_block=195}] ~ ~ ~ title @s actionbar §a§lBrush small acacia_door
execute @s [scores={paint_block=196}] ~ ~ ~ title @s actionbar §a§lBrush small dark_oak_door
execute @s [scores={paint_block=197}] ~ ~ ~ title @s actionbar §a§lBrush small end_rod
execute @s [scores={paint_block=198}] ~ ~ ~ title @s actionbar §a§lBrush small chorus_plant
execute @s [scores={paint_block=199}] ~ ~ ~ title @s actionbar §a§lBrush small chorus_flower
execute @s [scores={paint_block=200}] ~ ~ ~ title @s actionbar §a§lBrush small purpur_block
execute @s [scores={paint_block=201}] ~ ~ ~ title @s actionbar §a§lBrush small purpur_pillar
execute @s [scores={paint_block=202}] ~ ~ ~ title @s actionbar §a§lBrush small purpur_stairs
execute @s [scores={paint_block=203}] ~ ~ ~ title @s actionbar §a§lBrush small purpur_double_slab
execute @s [scores={paint_block=204}] ~ ~ ~ title @s actionbar §a§lBrush small purpur_slab
execute @s [scores={paint_block=205}] ~ ~ ~ title @s actionbar §a§lBrush small end_bricks
execute @s [scores={paint_block=206}] ~ ~ ~ title @s actionbar §a§lBrush small beetroots
execute @s [scores={paint_block=207}] ~ ~ ~ title @s actionbar §a§lBrush small grass_path
execute @s [scores={paint_block=208}] ~ ~ ~ title @s actionbar §a§lBrush small end_gateway
execute @s [scores={paint_block=209}] ~ ~ ~ title @s actionbar §a§lBrush small repeating_command_block
execute @s [scores={paint_block=210}] ~ ~ ~ title @s actionbar §a§lBrush small chain_command_block
execute @s [scores={paint_block=211}] ~ ~ ~ title @s actionbar §a§lBrush small frosted_ice
execute @s [scores={paint_block=212}] ~ ~ ~ title @s actionbar §a§lBrush small magma
execute @s [scores={paint_block=213}] ~ ~ ~ title @s actionbar §a§lBrush small nether_wart_block
execute @s [scores={paint_block=214}] ~ ~ ~ title @s actionbar §a§lBrush small red_nether_brick
execute @s [scores={paint_block=215}] ~ ~ ~ title @s actionbar §a§lBrush small bone_block
execute @s [scores={paint_block=216}] ~ ~ ~ title @s actionbar §a§lBrush small structure_void
execute @s [scores={paint_block=217}] ~ ~ ~ title @s actionbar §a§lBrush small observer
execute @s [scores={paint_block=218}] ~ ~ ~ title @s actionbar §a§lBrush small white_shulker_box
execute @s [scores={paint_block=219}] ~ ~ ~ title @s actionbar §a§lBrush small orange_shulker_box
execute @s [scores={paint_block=220}] ~ ~ ~ title @s actionbar §a§lBrush small magenta_shulker_box
execute @s [scores={paint_block=221}] ~ ~ ~ title @s actionbar §a§lBrush small light_blue_shulker_box
execute @s [scores={paint_block=222}] ~ ~ ~ title @s actionbar §a§lBrush small yellow_shulker_box
execute @s [scores={paint_block=223}] ~ ~ ~ title @s actionbar §a§lBrush small lime_shulker_box
execute @s [scores={paint_block=224}] ~ ~ ~ title @s actionbar §a§lBrush small pink_shulker_box
execute @s [scores={paint_block=225}] ~ ~ ~ title @s actionbar §a§lBrush small gray_shulker_box
execute @s [scores={paint_block=226}] ~ ~ ~ title @s actionbar §a§lBrush small silver_shulker_box
execute @s [scores={paint_block=227}] ~ ~ ~ title @s actionbar §a§lBrush small cyan_shulker_box
execute @s [scores={paint_block=228}] ~ ~ ~ title @s actionbar §a§lBrush small purple_shulker_box
execute @s [scores={paint_block=229}] ~ ~ ~ title @s actionbar §a§lBrush small blue_shulker_box
execute @s [scores={paint_block=230}] ~ ~ ~ title @s actionbar §a§lBrush small brown_shulker_box
execute @s [scores={paint_block=231}] ~ ~ ~ title @s actionbar §a§lBrush small green_shulker_box
execute @s [scores={paint_block=232}] ~ ~ ~ title @s actionbar §a§lBrush small red_shulker_box
execute @s [scores={paint_block=233}] ~ ~ ~ title @s actionbar §a§lBrush small black_shulker_box
execute @s [scores={paint_block=234}] ~ ~ ~ title @s actionbar §a§lBrush small white_glazed_terracotta
execute @s [scores={paint_block=235}] ~ ~ ~ title @s actionbar §a§lBrush small orange_glazed_terracotta
execute @s [scores={paint_block=236}] ~ ~ ~ title @s actionbar §a§lBrush small magenta_glazed_terracotta
execute @s [scores={paint_block=237}] ~ ~ ~ title @s actionbar §a§lBrush small light_blue_glazed_terracotta
execute @s [scores={paint_block=238}] ~ ~ ~ title @s actionbar §a§lBrush small yellow_glazed_terracotta
execute @s [scores={paint_block=239}] ~ ~ ~ title @s actionbar §a§lBrush small lime_glazed_terracotta
execute @s [scores={paint_block=240}] ~ ~ ~ title @s actionbar §a§lBrush small pink_glazed_terracotta
execute @s [scores={paint_block=241}] ~ ~ ~ title @s actionbar §a§lBrush small gray_glazed_terracotta
execute @s [scores={paint_block=242}] ~ ~ ~ title @s actionbar §a§lBrush small light_gray_glazed_terracotta
execute @s [scores={paint_block=243}] ~ ~ ~ title @s actionbar §a§lBrush small cyan_glazed_terracotta
execute @s [scores={paint_block=244}] ~ ~ ~ title @s actionbar §a§lBrush small purple_glazed_terracotta
execute @s [scores={paint_block=245}] ~ ~ ~ title @s actionbar §a§lBrush small blue_glazed_terracotta
execute @s [scores={paint_block=246}] ~ ~ ~ title @s actionbar §a§lBrush small brown_glazed_terracotta
execute @s [scores={paint_block=247}] ~ ~ ~ title @s actionbar §a§lBrush small green_glazed_terracotta
execute @s [scores={paint_block=248}] ~ ~ ~ title @s actionbar §a§lBrush small red_glazed_terracotta
execute @s [scores={paint_block=249}] ~ ~ ~ title @s actionbar §a§lBrush small black_glazed_terracotta
execute @s [scores={paint_block=250}] ~ ~ ~ title @s actionbar §a§lBrush small concrete
execute @s [scores={paint_block=251}] ~ ~ ~ title @s actionbar §a§lBrush small concrete_powder
execute @s [scores={paint_block=252}] ~ ~ ~ title @s actionbar §a§lBrush small structure_block
execute @s [scores={paint_block=253}] ~ ~ ~ title @s actionbar §a§lBrush small iron_shovel
execute @s [scores={paint_block=254}] ~ ~ ~ title @s actionbar §a§lBrush small iron_pickaxe
execute @s [scores={paint_block=255}] ~ ~ ~ title @s actionbar §a§lBrush small iron_axe
execute @s [scores={paint_block=256}] ~ ~ ~ title @s actionbar §a§lBrush small flint_and_steel
execute @s [scores={paint_block=257}] ~ ~ ~ title @s actionbar §a§lBrush small apple
execute @s [scores={paint_block=258}] ~ ~ ~ title @s actionbar §a§lBrush small bow
execute @s [scores={paint_block=259}] ~ ~ ~ title @s actionbar §a§lBrush small arrow
execute @s [scores={paint_block=260}] ~ ~ ~ title @s actionbar §a§lBrush small coal
execute @s [scores={paint_block=261}] ~ ~ ~ title @s actionbar §a§lBrush small diamond
execute @s [scores={paint_block=262}] ~ ~ ~ title @s actionbar §a§lBrush small iron_ingot
execute @s [scores={paint_block=263}] ~ ~ ~ title @s actionbar §a§lBrush small gold_ingot
execute @s [scores={paint_block=264}] ~ ~ ~ title @s actionbar §a§lBrush small iron_sword
execute @s [scores={paint_block=265}] ~ ~ ~ title @s actionbar §a§lBrush small wooden_sword
execute @s [scores={paint_block=266}] ~ ~ ~ title @s actionbar §a§lBrush small wooden_shovel
execute @s [scores={paint_block=267}] ~ ~ ~ title @s actionbar §a§lBrush small wooden_pickaxe
execute @s [scores={paint_block=268}] ~ ~ ~ title @s actionbar §a§lBrush small wooden_axe
execute @s [scores={paint_block=269}] ~ ~ ~ title @s actionbar §a§lBrush small stone_sword
execute @s [scores={paint_block=270}] ~ ~ ~ title @s actionbar §a§lBrush small stone_shovel
execute @s [scores={paint_block=271}] ~ ~ ~ title @s actionbar §a§lBrush small stone_pickaxe
execute @s [scores={paint_block=272}] ~ ~ ~ title @s actionbar §a§lBrush small stone_axe
execute @s [scores={paint_block=273}] ~ ~ ~ title @s actionbar §a§lBrush small diamond_sword
execute @s [scores={paint_block=274}] ~ ~ ~ title @s actionbar §a§lBrush small diamond_shovel
execute @s [scores={paint_block=275}] ~ ~ ~ title @s actionbar §a§lBrush small diamond_pickaxe
execute @s [scores={paint_block=276}] ~ ~ ~ title @s actionbar §a§lBrush small diamond_axe
execute @s [scores={paint_block=277}] ~ ~ ~ title @s actionbar §a§lBrush small stick
execute @s [scores={paint_block=278}] ~ ~ ~ title @s actionbar §a§lBrush small bowl
execute @s [scores={paint_block=279}] ~ ~ ~ title @s actionbar §a§lBrush small mushroom_stew
execute @s [scores={paint_block=280}] ~ ~ ~ title @s actionbar §a§lBrush small golden_sword
execute @s [scores={paint_block=281}] ~ ~ ~ title @s actionbar §a§lBrush small golden_shovel
execute @s [scores={paint_block=282}] ~ ~ ~ title @s actionbar §a§lBrush small golden_pickaxe
execute @s [scores={paint_block=283}] ~ ~ ~ title @s actionbar §a§lBrush small golden_axe
execute @s [scores={paint_block=284}] ~ ~ ~ title @s actionbar §a§lBrush small string
execute @s [scores={paint_block=285}] ~ ~ ~ title @s actionbar §a§lBrush small feather
execute @s [scores={paint_block=286}] ~ ~ ~ title @s actionbar §a§lBrush small gunpowder
execute @s [scores={paint_block=287}] ~ ~ ~ title @s actionbar §a§lBrush small wooden_hoe
execute @s [scores={paint_block=288}] ~ ~ ~ title @s actionbar §a§lBrush small stone_hoe
execute @s [scores={paint_block=289}] ~ ~ ~ title @s actionbar §a§lBrush small iron_hoe
execute @s [scores={paint_block=290}] ~ ~ ~ title @s actionbar §a§lBrush small diamond_hoe
execute @s [scores={paint_block=291}] ~ ~ ~ title @s actionbar §a§lBrush small golden_hoe
execute @s [scores={paint_block=292}] ~ ~ ~ title @s actionbar §a§lBrush small wheat_seeds
execute @s [scores={paint_block=293}] ~ ~ ~ title @s actionbar §a§lBrush small bread
execute @s [scores={paint_block=294}] ~ ~ ~ title @s actionbar §a§lBrush small leather_helmet
execute @s [scores={paint_block=295}] ~ ~ ~ title @s actionbar §a§lBrush small leather_chestplate
execute @s [scores={paint_block=296}] ~ ~ ~ title @s actionbar §a§lBrush small leather_leggings
execute @s [scores={paint_block=297}] ~ ~ ~ title @s actionbar §a§lBrush small leather_boots
execute @s [scores={paint_block=298}] ~ ~ ~ title @s actionbar §a§lBrush small chainmail_helmet
execute @s [scores={paint_block=299}] ~ ~ ~ title @s actionbar §a§lBrush small chainmail_chestplate
execute @s [scores={paint_block=300}] ~ ~ ~ title @s actionbar §a§lBrush small chainmail_leggings
execute @s [scores={paint_block=301}] ~ ~ ~ title @s actionbar §a§lBrush small chainmail_boots
execute @s [scores={paint_block=302}] ~ ~ ~ title @s actionbar §a§lBrush small iron_helmet
execute @s [scores={paint_block=303}] ~ ~ ~ title @s actionbar §a§lBrush small iron_chestplate
execute @s [scores={paint_block=304}] ~ ~ ~ title @s actionbar §a§lBrush small iron_leggings
execute @s [scores={paint_block=305}] ~ ~ ~ title @s actionbar §a§lBrush small iron_boots
execute @s [scores={paint_block=306}] ~ ~ ~ title @s actionbar §a§lBrush small diamond_helmet
execute @s [scores={paint_block=307}] ~ ~ ~ title @s actionbar §a§lBrush small diamond_chestplate
execute @s [scores={paint_block=308}] ~ ~ ~ title @s actionbar §a§lBrush small diamond_leggings
execute @s [scores={paint_block=309}] ~ ~ ~ title @s actionbar §a§lBrush small diamond_boots
execute @s [scores={paint_block=310}] ~ ~ ~ title @s actionbar §a§lBrush small golden_helmet
execute @s [scores={paint_block=311}] ~ ~ ~ title @s actionbar §a§lBrush small golden_chestplate
execute @s [scores={paint_block=312}] ~ ~ ~ title @s actionbar §a§lBrush small golden_leggings
execute @s [scores={paint_block=313}] ~ ~ ~ title @s actionbar §a§lBrush small golden_boots
execute @s [scores={paint_block=314}] ~ ~ ~ title @s actionbar §a§lBrush small flint
execute @s [scores={paint_block=315}] ~ ~ ~ title @s actionbar §a§lBrush small porkchop
execute @s [scores={paint_block=316}] ~ ~ ~ title @s actionbar §a§lBrush small cooked_porkchop
execute @s [scores={paint_block=317}] ~ ~ ~ title @s actionbar §a§lBrush small painting
execute @s [scores={paint_block=318}] ~ ~ ~ title @s actionbar §a§lBrush small golden_apple
execute @s [scores={paint_block=319}] ~ ~ ~ title @s actionbar §a§lBrush small sign
execute @s [scores={paint_block=320}] ~ ~ ~ title @s actionbar §a§lBrush small bucket
execute @s [scores={paint_block=321}] ~ ~ ~ title @s actionbar §a§lBrush small water_bucket
execute @s [scores={paint_block=322}] ~ ~ ~ title @s actionbar §a§lBrush small lava_bucket
execute @s [scores={paint_block=323}] ~ ~ ~ title @s actionbar §a§lBrush small minecart
execute @s [scores={paint_block=324}] ~ ~ ~ title @s actionbar §a§lBrush small saddle
execute @s [scores={paint_block=325}] ~ ~ ~ title @s actionbar §a§lBrush small redstone
execute @s [scores={paint_block=326}] ~ ~ ~ title @s actionbar §a§lBrush small snowball
execute @s [scores={paint_block=327}] ~ ~ ~ title @s actionbar §a§lBrush small boat
execute @s [scores={paint_block=328}] ~ ~ ~ title @s actionbar §a§lBrush small leather
execute @s [scores={paint_block=329}] ~ ~ ~ title @s actionbar §a§lBrush small milk_bucket
execute @s [scores={paint_block=330}] ~ ~ ~ title @s actionbar §a§lBrush small brick
execute @s [scores={paint_block=331}] ~ ~ ~ title @s actionbar §a§lBrush small clay_ball
execute @s [scores={paint_block=332}] ~ ~ ~ title @s actionbar §a§lBrush small paper
execute @s [scores={paint_block=333}] ~ ~ ~ title @s actionbar §a§lBrush small book
execute @s [scores={paint_block=334}] ~ ~ ~ title @s actionbar §a§lBrush small slime_ball
execute @s [scores={paint_block=335}] ~ ~ ~ title @s actionbar §a§lBrush small chest_minecart
execute @s [scores={paint_block=336}] ~ ~ ~ title @s actionbar §a§lBrush small furnace_minecart
execute @s [scores={paint_block=337}] ~ ~ ~ title @s actionbar §a§lBrush small egg
execute @s [scores={paint_block=338}] ~ ~ ~ title @s actionbar §a§lBrush small compass
execute @s [scores={paint_block=339}] ~ ~ ~ title @s actionbar §a§lBrush small fishing_rod
execute @s [scores={paint_block=340}] ~ ~ ~ title @s actionbar §a§lBrush small clock
execute @s [scores={paint_block=341}] ~ ~ ~ title @s actionbar §a§lBrush small glowstone_dust
execute @s [scores={paint_block=342}] ~ ~ ~ title @s actionbar §a§lBrush small fish
execute @s [scores={paint_block=343}] ~ ~ ~ title @s actionbar §a§lBrush small cooked_fish
execute @s [scores={paint_block=344}] ~ ~ ~ title @s actionbar §a§lBrush small dye
execute @s [scores={paint_block=345}] ~ ~ ~ title @s actionbar §a§lBrush small bone
execute @s [scores={paint_block=346}] ~ ~ ~ title @s actionbar §a§lBrush small sugar
execute @s [scores={paint_block=347}] ~ ~ ~ title @s actionbar §a§lBrush small repeater
execute @s [scores={paint_block=348}] ~ ~ ~ title @s actionbar §a§lBrush small cookie
execute @s [scores={paint_block=349}] ~ ~ ~ title @s actionbar §a§lBrush small filled_map
execute @s [scores={paint_block=350}] ~ ~ ~ title @s actionbar §a§lBrush small shears
execute @s [scores={paint_block=351}] ~ ~ ~ title @s actionbar §a§lBrush small melon
execute @s [scores={paint_block=352}] ~ ~ ~ title @s actionbar §a§lBrush small pumpkin_seeds
execute @s [scores={paint_block=353}] ~ ~ ~ title @s actionbar §a§lBrush small melon_seeds
execute @s [scores={paint_block=354}] ~ ~ ~ title @s actionbar §a§lBrush small beef
execute @s [scores={paint_block=355}] ~ ~ ~ title @s actionbar §a§lBrush small cooked_beef
execute @s [scores={paint_block=356}] ~ ~ ~ title @s actionbar §a§lBrush small chicken
execute @s [scores={paint_block=357}] ~ ~ ~ title @s actionbar §a§lBrush small cooked_chicken
execute @s [scores={paint_block=358}] ~ ~ ~ title @s actionbar §a§lBrush small rotten_flesh
execute @s [scores={paint_block=359}] ~ ~ ~ title @s actionbar §a§lBrush small ender_pearl
execute @s [scores={paint_block=360}] ~ ~ ~ title @s actionbar §a§lBrush small blaze_rod
execute @s [scores={paint_block=361}] ~ ~ ~ title @s actionbar §a§lBrush small ghast_tear
execute @s [scores={paint_block=362}] ~ ~ ~ title @s actionbar §a§lBrush small gold_nugget
execute @s [scores={paint_block=363}] ~ ~ ~ title @s actionbar §a§lBrush small potion
execute @s [scores={paint_block=364}] ~ ~ ~ title @s actionbar §a§lBrush small glass_bottle
execute @s [scores={paint_block=365}] ~ ~ ~ title @s actionbar §a§lBrush small spider_eye
execute @s [scores={paint_block=366}] ~ ~ ~ title @s actionbar §a§lBrush small fermented_spider_eye
execute @s [scores={paint_block=367}] ~ ~ ~ title @s actionbar §a§lBrush small blaze_powder
execute @s [scores={paint_block=368}] ~ ~ ~ title @s actionbar §a§lBrush small magma_cream
execute @s [scores={paint_block=369}] ~ ~ ~ title @s actionbar §a§lBrush small ender_eye
execute @s [scores={paint_block=370}] ~ ~ ~ title @s actionbar §a§lBrush small speckled_melon
execute @s [scores={paint_block=371}] ~ ~ ~ title @s actionbar §a§lBrush small spawn_egg
execute @s [scores={paint_block=372}] ~ ~ ~ title @s actionbar §a§lBrush small experience_bottle
execute @s [scores={paint_block=373}] ~ ~ ~ title @s actionbar §a§lBrush small fire_charge
execute @s [scores={paint_block=374}] ~ ~ ~ title @s actionbar §a§lBrush small writable_book
execute @s [scores={paint_block=375}] ~ ~ ~ title @s actionbar §a§lBrush small written_book
execute @s [scores={paint_block=376}] ~ ~ ~ title @s actionbar §a§lBrush small emerald
execute @s [scores={paint_block=377}] ~ ~ ~ title @s actionbar §a§lBrush small item_frame
execute @s [scores={paint_block=378}] ~ ~ ~ title @s actionbar §a§lBrush small carrot
execute @s [scores={paint_block=379}] ~ ~ ~ title @s actionbar §a§lBrush small potato
execute @s [scores={paint_block=380}] ~ ~ ~ title @s actionbar §a§lBrush small baked_potato
execute @s [scores={paint_block=381}] ~ ~ ~ title @s actionbar §a§lBrush small poisonous_potato
execute @s [scores={paint_block=382}] ~ ~ ~ title @s actionbar §a§lBrush small map
execute @s [scores={paint_block=383}] ~ ~ ~ title @s actionbar §a§lBrush small golden_carrot
execute @s [scores={paint_block=384}] ~ ~ ~ title @s actionbar §a§lBrush small carrot_on_a_stick
execute @s [scores={paint_block=385}] ~ ~ ~ title @s actionbar §a§lBrush small nether_star
execute @s [scores={paint_block=386}] ~ ~ ~ title @s actionbar §a§lBrush small pumpkin_pie
execute @s [scores={paint_block=387}] ~ ~ ~ title @s actionbar §a§lBrush small fireworks
execute @s [scores={paint_block=388}] ~ ~ ~ title @s actionbar §a§lBrush small firework_charge
execute @s [scores={paint_block=389}] ~ ~ ~ title @s actionbar §a§lBrush small enchanted_book
execute @s [scores={paint_block=390}] ~ ~ ~ title @s actionbar §a§lBrush small comparator
execute @s [scores={paint_block=391}] ~ ~ ~ title @s actionbar §a§lBrush small netherbrick
execute @s [scores={paint_block=392}] ~ ~ ~ title @s actionbar §a§lBrush small quartz
execute @s [scores={paint_block=393}] ~ ~ ~ title @s actionbar §a§lBrush small tnt_minecart
execute @s [scores={paint_block=394}] ~ ~ ~ title @s actionbar §a§lBrush small hopper_minecart
execute @s [scores={paint_block=395}] ~ ~ ~ title @s actionbar §a§lBrush small prismarine_shard
execute @s [scores={paint_block=396}] ~ ~ ~ title @s actionbar §a§lBrush small prismarine_crystals
execute @s [scores={paint_block=397}] ~ ~ ~ title @s actionbar §a§lBrush small rabbit
execute @s [scores={paint_block=398}] ~ ~ ~ title @s actionbar §a§lBrush small cooked_rabbit
execute @s [scores={paint_block=399}] ~ ~ ~ title @s actionbar §a§lBrush small rabbit_stew
execute @s [scores={paint_block=400}] ~ ~ ~ title @s actionbar §a§lBrush small rabbit_foot
execute @s [scores={paint_block=401}] ~ ~ ~ title @s actionbar §a§lBrush small rabbit_hide
execute @s [scores={paint_block=402}] ~ ~ ~ title @s actionbar §a§lBrush small armor_stand
execute @s [scores={paint_block=403}] ~ ~ ~ title @s actionbar §a§lBrush small iron_horse_armor
execute @s [scores={paint_block=404}] ~ ~ ~ title @s actionbar §a§lBrush small golden_horse_armor
execute @s [scores={paint_block=405}] ~ ~ ~ title @s actionbar §a§lBrush small diamond_horse_armor
execute @s [scores={paint_block=406}] ~ ~ ~ title @s actionbar §a§lBrush small lead
execute @s [scores={paint_block=407}] ~ ~ ~ title @s actionbar §a§lBrush small name_tag
execute @s [scores={paint_block=408}] ~ ~ ~ title @s actionbar §a§lBrush small command_block_minecart
execute @s [scores={paint_block=409}] ~ ~ ~ title @s actionbar §a§lBrush small mutton
execute @s [scores={paint_block=410}] ~ ~ ~ title @s actionbar §a§lBrush small cooked_mutton
execute @s [scores={paint_block=411}] ~ ~ ~ title @s actionbar §a§lBrush small banner
execute @s [scores={paint_block=412}] ~ ~ ~ title @s actionbar §a§lBrush small end_crystal
execute @s [scores={paint_block=413}] ~ ~ ~ title @s actionbar §a§lBrush small chorus_fruit
execute @s [scores={paint_block=414}] ~ ~ ~ title @s actionbar §a§lBrush small popped_chorus_fruit
execute @s [scores={paint_block=415}] ~ ~ ~ title @s actionbar §a§lBrush small beetroot
execute @s [scores={paint_block=416}] ~ ~ ~ title @s actionbar §a§lBrush small beetroot_seeds
execute @s [scores={paint_block=417}] ~ ~ ~ title @s actionbar §a§lBrush small beetroot_soup
execute @s [scores={paint_block=418}] ~ ~ ~ title @s actionbar §a§lBrush small dragon_breath
execute @s [scores={paint_block=419}] ~ ~ ~ title @s actionbar §a§lBrush small splash_potion
execute @s [scores={paint_block=420}] ~ ~ ~ title @s actionbar §a§lBrush small spectral_arrow
execute @s [scores={paint_block=421}] ~ ~ ~ title @s actionbar §a§lBrush small tipped_arrow
execute @s [scores={paint_block=422}] ~ ~ ~ title @s actionbar §a§lBrush small lingering_potion
execute @s [scores={paint_block=423}] ~ ~ ~ title @s actionbar §a§lBrush small shield
execute @s [scores={paint_block=424}] ~ ~ ~ title @s actionbar §a§lBrush small elytra
execute @s [scores={paint_block=425}] ~ ~ ~ title @s actionbar §a§lBrush small spruce_boat
execute @s [scores={paint_block=426}] ~ ~ ~ title @s actionbar §a§lBrush small birch_boat
execute @s [scores={paint_block=427}] ~ ~ ~ title @s actionbar §a§lBrush small jungle_boat
execute @s [scores={paint_block=428}] ~ ~ ~ title @s actionbar §a§lBrush small acacia_boat
execute @s [scores={paint_block=429}] ~ ~ ~ title @s actionbar §a§lBrush small dark_oak_boat
execute @s [scores={paint_block=430}] ~ ~ ~ title @s actionbar §a§lBrush small totem_of_undying
execute @s [scores={paint_block=431}] ~ ~ ~ title @s actionbar §a§lBrush small shulker_shell
execute @s [scores={paint_block=432}] ~ ~ ~ title @s actionbar §a§lBrush small iron_nugget
execute @s [scores={paint_block=433}] ~ ~ ~ title @s actionbar §a§lBrush small knowledge_book
execute @s [scores={paint_block=434}] ~ ~ ~ title @s actionbar §a§lBrush small record_13
execute @s [scores={paint_block=435}] ~ ~ ~ title @s actionbar §a§lBrush small record_cat
execute @s [scores={paint_block=436}] ~ ~ ~ title @s actionbar §a§lBrush small record_blocks
execute @s [scores={paint_block=437}] ~ ~ ~ title @s actionbar §a§lBrush small record_chirp
execute @s [scores={paint_block=438}] ~ ~ ~ title @s actionbar §a§lBrush small record_far
execute @s [scores={paint_block=439}] ~ ~ ~ title @s actionbar §a§lBrush small record_mall
execute @s [scores={paint_block=440}] ~ ~ ~ title @s actionbar §a§lBrush small record_mellohi
execute @s [scores={paint_block=441}] ~ ~ ~ title @s actionbar §a§lBrush small record_stal
execute @s [scores={paint_block=442}] ~ ~ ~ title @s actionbar §a§lBrush small record_strad
execute @s [scores={paint_block=443}] ~ ~ ~ title @s actionbar §a§lBrush small record_ward
execute @s [scores={paint_block=444}] ~ ~ ~ title @s actionbar §a§lBrush small record_11
execute @s [scores={paint_block=445}] ~ ~ ~ title @s actionbar §a§lBrush small record_wait