execute @s [scores={paint_block=1}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_1
execute @s [scores={paint_block=2}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_2
execute @s [scores={paint_block=3}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_3
execute @s [scores={paint_block=4}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_4
execute @s [scores={paint_block=5}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_5
execute @s [scores={paint_block=6}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_6
execute @s [scores={paint_block=7}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_7
execute @s [scores={paint_block=8}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_8
execute @s [scores={paint_block=9}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_9
execute @s [scores={paint_block=10}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_10
execute @s [scores={paint_block=11}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_11
execute @s [scores={paint_block=12}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_12
execute @s [scores={paint_block=13}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_13
execute @s [scores={paint_block=14}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_14
execute @s [scores={paint_block=15}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_15
execute @s [scores={paint_block=16}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_16
execute @s [scores={paint_block=17}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_17
execute @s [scores={paint_block=18}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_18
execute @s [scores={paint_block=19}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_19
execute @s [scores={paint_block=20}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_20
execute @s [scores={paint_block=21}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_21
execute @s [scores={paint_block=22}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_22
execute @s [scores={paint_block=23}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_23
execute @s [scores={paint_block=24}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_24
execute @s [scores={paint_block=25}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_25
execute @s [scores={paint_block=26}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_26
execute @s [scores={paint_block=27}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_27
execute @s [scores={paint_block=28}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_28
execute @s [scores={paint_block=29}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_29
execute @s [scores={paint_block=30}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_30
execute @s [scores={paint_block=31}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_31
execute @s [scores={paint_block=32}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_32
execute @s [scores={paint_block=33}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_33
execute @s [scores={paint_block=34}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_34
execute @s [scores={paint_block=35}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_35
execute @s [scores={paint_block=36}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_36
execute @s [scores={paint_block=37}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_37
execute @s [scores={paint_block=38}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_38
execute @s [scores={paint_block=39}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_39
execute @s [scores={paint_block=40}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_40
execute @s [scores={paint_block=41}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_41
execute @s [scores={paint_block=42}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_42
execute @s [scores={paint_block=43}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_43
execute @s [scores={paint_block=44}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_44
execute @s [scores={paint_block=45}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_45
execute @s [scores={paint_block=46}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_46
execute @s [scores={paint_block=47}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_47
execute @s [scores={paint_block=48}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_48
execute @s [scores={paint_block=49}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_49
execute @s [scores={paint_block=50}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_50
execute @s [scores={paint_block=51}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_51
execute @s [scores={paint_block=52}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_52
execute @s [scores={paint_block=53}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_53
execute @s [scores={paint_block=54}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_54
execute @s [scores={paint_block=55}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_55
execute @s [scores={paint_block=56}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_56
execute @s [scores={paint_block=57}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_57
execute @s [scores={paint_block=58}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_58
execute @s [scores={paint_block=59}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_59
execute @s [scores={paint_block=60}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_60
execute @s [scores={paint_block=61}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_61
execute @s [scores={paint_block=62}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_62
execute @s [scores={paint_block=63}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_63
execute @s [scores={paint_block=64}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_64
execute @s [scores={paint_block=65}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_65
execute @s [scores={paint_block=66}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_66
execute @s [scores={paint_block=67}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_67
execute @s [scores={paint_block=68}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_68
execute @s [scores={paint_block=69}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_69
execute @s [scores={paint_block=70}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_70
execute @s [scores={paint_block=71}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_71
execute @s [scores={paint_block=72}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_72
execute @s [scores={paint_block=73}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_73
execute @s [scores={paint_block=74}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_74
execute @s [scores={paint_block=75}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_75
execute @s [scores={paint_block=76}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_76
execute @s [scores={paint_block=77}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_77
execute @s [scores={paint_block=78}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_78
execute @s [scores={paint_block=79}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_79
execute @s [scores={paint_block=80}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_80
execute @s [scores={paint_block=81}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_81
execute @s [scores={paint_block=82}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_82
execute @s [scores={paint_block=83}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_83
execute @s [scores={paint_block=84}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_84
execute @s [scores={paint_block=85}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_85
execute @s [scores={paint_block=86}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_86
execute @s [scores={paint_block=87}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_87
execute @s [scores={paint_block=88}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_88
execute @s [scores={paint_block=89}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_89
execute @s [scores={paint_block=90}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_90
execute @s [scores={paint_block=91}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_91
execute @s [scores={paint_block=92}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_92
execute @s [scores={paint_block=93}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_93
execute @s [scores={paint_block=94}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_94
execute @s [scores={paint_block=95}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_95
execute @s [scores={paint_block=96}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_96
execute @s [scores={paint_block=97}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_97
execute @s [scores={paint_block=98}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_98
execute @s [scores={paint_block=99}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_99
execute @s [scores={paint_block=100}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_100
execute @s [scores={paint_block=101}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_101
execute @s [scores={paint_block=102}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_102
execute @s [scores={paint_block=103}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_103
execute @s [scores={paint_block=104}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_104
execute @s [scores={paint_block=105}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_105
execute @s [scores={paint_block=106}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_106
execute @s [scores={paint_block=107}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_107
execute @s [scores={paint_block=108}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_108
execute @s [scores={paint_block=109}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_109
execute @s [scores={paint_block=110}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_110
execute @s [scores={paint_block=111}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_111
execute @s [scores={paint_block=112}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_112
execute @s [scores={paint_block=113}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_113
execute @s [scores={paint_block=114}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_114
execute @s [scores={paint_block=115}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_115
execute @s [scores={paint_block=116}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_116
execute @s [scores={paint_block=117}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_117
execute @s [scores={paint_block=118}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_118
execute @s [scores={paint_block=119}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_119
execute @s [scores={paint_block=120}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_120
execute @s [scores={paint_block=121}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_121
execute @s [scores={paint_block=122}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_122
execute @s [scores={paint_block=123}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_123
execute @s [scores={paint_block=124}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_124
execute @s [scores={paint_block=125}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_125
execute @s [scores={paint_block=126}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_126
execute @s [scores={paint_block=127}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_127
execute @s [scores={paint_block=128}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_128
execute @s [scores={paint_block=129}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_129
execute @s [scores={paint_block=130}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_130
execute @s [scores={paint_block=131}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_131
execute @s [scores={paint_block=132}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_132
execute @s [scores={paint_block=133}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_133
execute @s [scores={paint_block=134}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_134
execute @s [scores={paint_block=135}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_135
execute @s [scores={paint_block=136}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_136
execute @s [scores={paint_block=137}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_137
execute @s [scores={paint_block=138}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_138
execute @s [scores={paint_block=139}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_139
execute @s [scores={paint_block=140}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_140
execute @s [scores={paint_block=141}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_141
execute @s [scores={paint_block=142}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_142
execute @s [scores={paint_block=143}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_143
execute @s [scores={paint_block=144}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_144
execute @s [scores={paint_block=145}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_145
execute @s [scores={paint_block=146}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_146
execute @s [scores={paint_block=147}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_147
execute @s [scores={paint_block=148}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_148
execute @s [scores={paint_block=149}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_149
execute @s [scores={paint_block=150}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_150
execute @s [scores={paint_block=151}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_151
execute @s [scores={paint_block=152}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_152
execute @s [scores={paint_block=153}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_153
execute @s [scores={paint_block=154}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_154
execute @s [scores={paint_block=155}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_155
execute @s [scores={paint_block=156}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_156
execute @s [scores={paint_block=157}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_157
execute @s [scores={paint_block=158}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_158
execute @s [scores={paint_block=159}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_159
execute @s [scores={paint_block=160}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_160
execute @s [scores={paint_block=161}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_161
execute @s [scores={paint_block=162}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_162
execute @s [scores={paint_block=163}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_163
execute @s [scores={paint_block=164}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_164
execute @s [scores={paint_block=165}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_165
execute @s [scores={paint_block=166}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_166
execute @s [scores={paint_block=167}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_167
execute @s [scores={paint_block=168}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_168
execute @s [scores={paint_block=169}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_169
execute @s [scores={paint_block=170}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_170
execute @s [scores={paint_block=171}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_171
execute @s [scores={paint_block=172}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_172
execute @s [scores={paint_block=173}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_173
execute @s [scores={paint_block=174}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_174
execute @s [scores={paint_block=175}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_175
execute @s [scores={paint_block=176}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_176
execute @s [scores={paint_block=177}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_177
execute @s [scores={paint_block=178}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_178
execute @s [scores={paint_block=179}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_179
execute @s [scores={paint_block=180}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_180
execute @s [scores={paint_block=181}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_181
execute @s [scores={paint_block=182}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_182
execute @s [scores={paint_block=183}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_183
execute @s [scores={paint_block=184}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_184
execute @s [scores={paint_block=185}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_185
execute @s [scores={paint_block=186}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_186
execute @s [scores={paint_block=187}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_187
execute @s [scores={paint_block=188}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_188
execute @s [scores={paint_block=189}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_189
execute @s [scores={paint_block=190}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_190
execute @s [scores={paint_block=191}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_191
execute @s [scores={paint_block=192}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_192
execute @s [scores={paint_block=193}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_193
execute @s [scores={paint_block=194}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_194
execute @s [scores={paint_block=195}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_195
execute @s [scores={paint_block=196}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_196
execute @s [scores={paint_block=197}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_197
execute @s [scores={paint_block=198}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_198
execute @s [scores={paint_block=199}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_199
execute @s [scores={paint_block=200}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_200
execute @s [scores={paint_block=201}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_201
execute @s [scores={paint_block=202}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_202
execute @s [scores={paint_block=203}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_203
execute @s [scores={paint_block=204}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_204
execute @s [scores={paint_block=205}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_205
execute @s [scores={paint_block=206}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_206
execute @s [scores={paint_block=207}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_207
execute @s [scores={paint_block=208}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_208
execute @s [scores={paint_block=209}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_209
execute @s [scores={paint_block=210}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_210
execute @s [scores={paint_block=211}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_211
execute @s [scores={paint_block=212}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_212
execute @s [scores={paint_block=213}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_213
execute @s [scores={paint_block=214}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_214
execute @s [scores={paint_block=215}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_215
execute @s [scores={paint_block=216}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_216
execute @s [scores={paint_block=217}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_217
execute @s [scores={paint_block=218}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_218
execute @s [scores={paint_block=219}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_219
execute @s [scores={paint_block=220}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_220
execute @s [scores={paint_block=221}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_221
execute @s [scores={paint_block=222}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_222
execute @s [scores={paint_block=223}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_223
execute @s [scores={paint_block=224}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_224
execute @s [scores={paint_block=225}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_225
execute @s [scores={paint_block=226}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_226
execute @s [scores={paint_block=227}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_227
execute @s [scores={paint_block=228}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_228
execute @s [scores={paint_block=229}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_229
execute @s [scores={paint_block=230}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_230
execute @s [scores={paint_block=231}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_231
execute @s [scores={paint_block=232}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_232
execute @s [scores={paint_block=233}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_233
execute @s [scores={paint_block=234}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_234
execute @s [scores={paint_block=235}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_235
execute @s [scores={paint_block=236}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_236
execute @s [scores={paint_block=237}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_237
execute @s [scores={paint_block=238}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_238
execute @s [scores={paint_block=239}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_239
execute @s [scores={paint_block=240}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_240
execute @s [scores={paint_block=241}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_241
execute @s [scores={paint_block=242}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_242
execute @s [scores={paint_block=243}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_243
execute @s [scores={paint_block=244}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_244
execute @s [scores={paint_block=245}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_245
execute @s [scores={paint_block=246}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_246
execute @s [scores={paint_block=247}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_247
execute @s [scores={paint_block=248}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_248
execute @s [scores={paint_block=249}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_249
execute @s [scores={paint_block=250}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_250
execute @s [scores={paint_block=251}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_251
execute @s [scores={paint_block=252}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_252
execute @s [scores={paint_block=253}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_253
execute @s [scores={paint_block=254}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_254
execute @s [scores={paint_block=255}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_255
execute @s [scores={paint_block=256}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_256
execute @s [scores={paint_block=257}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_257
execute @s [scores={paint_block=258}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_258
execute @s [scores={paint_block=259}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_259
execute @s [scores={paint_block=260}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_260
execute @s [scores={paint_block=261}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_261
execute @s [scores={paint_block=262}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_262
execute @s [scores={paint_block=263}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_263
execute @s [scores={paint_block=264}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_264
execute @s [scores={paint_block=265}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_265
execute @s [scores={paint_block=266}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_266
execute @s [scores={paint_block=267}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_267
execute @s [scores={paint_block=268}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_268
execute @s [scores={paint_block=269}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_269
execute @s [scores={paint_block=270}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_270
execute @s [scores={paint_block=271}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_271
execute @s [scores={paint_block=272}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_272
execute @s [scores={paint_block=273}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_273
execute @s [scores={paint_block=274}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_274
execute @s [scores={paint_block=275}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_275
execute @s [scores={paint_block=276}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_276
execute @s [scores={paint_block=277}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_277
execute @s [scores={paint_block=278}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_278
execute @s [scores={paint_block=279}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_279
execute @s [scores={paint_block=280}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_280
execute @s [scores={paint_block=281}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_281
execute @s [scores={paint_block=282}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_282
execute @s [scores={paint_block=283}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_283
execute @s [scores={paint_block=284}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_284
execute @s [scores={paint_block=285}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_285
execute @s [scores={paint_block=286}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_286
execute @s [scores={paint_block=287}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_287
execute @s [scores={paint_block=288}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_288
execute @s [scores={paint_block=289}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_289
execute @s [scores={paint_block=290}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_290
execute @s [scores={paint_block=291}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_291
execute @s [scores={paint_block=292}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_292
execute @s [scores={paint_block=293}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_293
execute @s [scores={paint_block=294}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_294
execute @s [scores={paint_block=295}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_295
execute @s [scores={paint_block=296}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_296
execute @s [scores={paint_block=297}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_297
execute @s [scores={paint_block=298}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_298
execute @s [scores={paint_block=299}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_299
execute @s [scores={paint_block=300}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_300
execute @s [scores={paint_block=301}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_301
execute @s [scores={paint_block=302}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_302
execute @s [scores={paint_block=303}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_303
execute @s [scores={paint_block=304}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_304
execute @s [scores={paint_block=305}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_305
execute @s [scores={paint_block=306}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_306
execute @s [scores={paint_block=307}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_307
execute @s [scores={paint_block=308}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_308
execute @s [scores={paint_block=309}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_309
execute @s [scores={paint_block=310}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_310
execute @s [scores={paint_block=311}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_311
execute @s [scores={paint_block=312}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_312
execute @s [scores={paint_block=313}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_313
execute @s [scores={paint_block=314}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_314
execute @s [scores={paint_block=315}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_315
execute @s [scores={paint_block=316}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_316
execute @s [scores={paint_block=317}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_317
execute @s [scores={paint_block=318}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_318
execute @s [scores={paint_block=319}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_319
execute @s [scores={paint_block=320}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_320
execute @s [scores={paint_block=321}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_321
execute @s [scores={paint_block=322}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_322
execute @s [scores={paint_block=323}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_323
execute @s [scores={paint_block=324}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_324
execute @s [scores={paint_block=325}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_325
execute @s [scores={paint_block=326}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_326
execute @s [scores={paint_block=327}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_327
execute @s [scores={paint_block=328}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_328
execute @s [scores={paint_block=329}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_329
execute @s [scores={paint_block=330}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_330
execute @s [scores={paint_block=331}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_331
execute @s [scores={paint_block=332}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_332
execute @s [scores={paint_block=333}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_333
execute @s [scores={paint_block=334}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_334
execute @s [scores={paint_block=335}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_335
execute @s [scores={paint_block=336}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_336
execute @s [scores={paint_block=337}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_337
execute @s [scores={paint_block=338}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_338
execute @s [scores={paint_block=339}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_339
execute @s [scores={paint_block=340}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_340
execute @s [scores={paint_block=341}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_341
execute @s [scores={paint_block=342}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_342
execute @s [scores={paint_block=343}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_343
execute @s [scores={paint_block=344}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_344
execute @s [scores={paint_block=345}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_345
execute @s [scores={paint_block=346}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_346
execute @s [scores={paint_block=347}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_347
execute @s [scores={paint_block=348}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_348
execute @s [scores={paint_block=349}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_349
execute @s [scores={paint_block=350}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_350
execute @s [scores={paint_block=351}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_351
execute @s [scores={paint_block=352}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_352
execute @s [scores={paint_block=353}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_353
execute @s [scores={paint_block=354}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_354
execute @s [scores={paint_block=355}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_355
execute @s [scores={paint_block=356}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_356
execute @s [scores={paint_block=357}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_357
execute @s [scores={paint_block=358}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_358
execute @s [scores={paint_block=359}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_359
execute @s [scores={paint_block=360}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_360
execute @s [scores={paint_block=361}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_361
execute @s [scores={paint_block=362}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_362
execute @s [scores={paint_block=363}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_363
execute @s [scores={paint_block=364}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_364
execute @s [scores={paint_block=365}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_365
execute @s [scores={paint_block=366}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_366
execute @s [scores={paint_block=367}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_367
execute @s [scores={paint_block=368}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_368
execute @s [scores={paint_block=369}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_369
execute @s [scores={paint_block=370}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_370
execute @s [scores={paint_block=371}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_371
execute @s [scores={paint_block=372}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_372
execute @s [scores={paint_block=373}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_373
execute @s [scores={paint_block=374}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_374
execute @s [scores={paint_block=375}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_375
execute @s [scores={paint_block=376}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_376
execute @s [scores={paint_block=377}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_377
execute @s [scores={paint_block=378}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_378
execute @s [scores={paint_block=379}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_379
execute @s [scores={paint_block=380}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_380
execute @s [scores={paint_block=381}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_381
execute @s [scores={paint_block=382}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_382
execute @s [scores={paint_block=383}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_383
execute @s [scores={paint_block=384}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_384
execute @s [scores={paint_block=385}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_385
execute @s [scores={paint_block=386}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_386
execute @s [scores={paint_block=387}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_387
execute @s [scores={paint_block=388}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_388
execute @s [scores={paint_block=389}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_389
execute @s [scores={paint_block=390}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_390
execute @s [scores={paint_block=391}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_391
execute @s [scores={paint_block=392}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_392
execute @s [scores={paint_block=393}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_393
execute @s [scores={paint_block=394}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_394
execute @s [scores={paint_block=395}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_395
execute @s [scores={paint_block=396}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_396
execute @s [scores={paint_block=397}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_397
execute @s [scores={paint_block=398}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_398
execute @s [scores={paint_block=399}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_399
execute @s [scores={paint_block=400}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_400
execute @s [scores={paint_block=401}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_401
execute @s [scores={paint_block=402}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_402
execute @s [scores={paint_block=403}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_403
execute @s [scores={paint_block=404}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_404
execute @s [scores={paint_block=405}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_405
execute @s [scores={paint_block=406}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_406
execute @s [scores={paint_block=407}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_407
execute @s [scores={paint_block=408}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_408
execute @s [scores={paint_block=409}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_409
execute @s [scores={paint_block=410}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_410
execute @s [scores={paint_block=411}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_411
execute @s [scores={paint_block=412}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_412
execute @s [scores={paint_block=413}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_413
execute @s [scores={paint_block=414}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_414
execute @s [scores={paint_block=415}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_415
execute @s [scores={paint_block=416}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_416
execute @s [scores={paint_block=417}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_417
execute @s [scores={paint_block=418}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_418
execute @s [scores={paint_block=419}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_419
execute @s [scores={paint_block=420}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_420
execute @s [scores={paint_block=421}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_421
execute @s [scores={paint_block=422}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_422
execute @s [scores={paint_block=423}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_423
execute @s [scores={paint_block=424}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_424
execute @s [scores={paint_block=425}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_425
execute @s [scores={paint_block=426}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_426
execute @s [scores={paint_block=427}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_427
execute @s [scores={paint_block=428}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_428
execute @s [scores={paint_block=429}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_429
execute @s [scores={paint_block=430}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_430
execute @s [scores={paint_block=431}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_431
execute @s [scores={paint_block=432}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_432
execute @s [scores={paint_block=433}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_433
execute @s [scores={paint_block=434}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_434
execute @s [scores={paint_block=435}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_435
execute @s [scores={paint_block=436}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_436
execute @s [scores={paint_block=437}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_437
execute @s [scores={paint_block=438}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_438
execute @s [scores={paint_block=439}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_439
execute @s [scores={paint_block=440}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_440
execute @s [scores={paint_block=441}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_441
execute @s [scores={paint_block=442}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_442
execute @s [scores={paint_block=443}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_443
execute @s [scores={paint_block=444}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_444
execute @s [scores={paint_block=445}] ~ ~ ~ function _processes/_brushes/_small/_mask_off/block_445