execute @s [scores={paint_block=1}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=2}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=3}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=4}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=5}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=6}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=7}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=8}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=9}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=10}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=11}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=12}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=13}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=14}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=15}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=16}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=17}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=18}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=19}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=20}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=21}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=22}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=23}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=24}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=25}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=26}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=27}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=28}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=29}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=30}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=31}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=32}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=33}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=34}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=35}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=36}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=37}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=38}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=39}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=40}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=41}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=42}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=43}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=44}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=45}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=46}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=47}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=48}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=49}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=50}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=51}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=52}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=53}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=54}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=55}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=56}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=57}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=58}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=59}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=60}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=61}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=62}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=63}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=64}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=65}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=66}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=67}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=68}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=69}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=70}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=71}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=72}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=73}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=74}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=75}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=76}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=77}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=78}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=79}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=80}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=81}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=82}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=83}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=84}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=85}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=86}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=87}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=88}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=89}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=90}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=91}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=92}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=93}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=94}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=95}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=96}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=97}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=98}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=99}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=100}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=101}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=102}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=103}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=104}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=105}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=106}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=107}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=108}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=109}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=110}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=111}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=112}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=113}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=114}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=115}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=116}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=117}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=118}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=119}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=120}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=121}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=122}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=123}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=124}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=125}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=126}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=127}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=128}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=129}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=130}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=131}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=132}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=133}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=134}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=135}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=136}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=137}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=138}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=139}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=140}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=141}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=142}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=143}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=144}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=145}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=146}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=147}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=148}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=149}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=150}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=151}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=152}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=153}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=154}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=155}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=156}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=157}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=158}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=159}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=160}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=161}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=162}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=163}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=164}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=165}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=166}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=167}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=168}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=169}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=170}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=171}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=172}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=173}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=174}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=175}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=176}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=177}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=178}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=179}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=180}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=181}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=182}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=183}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=184}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=185}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=186}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=187}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass
execute @s [scores={paint_block=188}, scores={mask_block=0] ~ ~ ~ function _processes/_brushes/_small/_mask_on/grass